version: "3"
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3-management
        volumes:
            - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
        ports:
            - "5672:5672"
            - "15672:15672"
    redis:
        hostname: redis
        image: redis:latest
        ports:
            - "6379:6379"
    flower:
        image: mher/flower
        # build:
        #     context: .
        #     dockerfile: flower.dockerfile
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_CELERY_DB_INDEX=10
            - REDIS_STORE_DB_INDEX=0
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_USERNAME=guest
            - RABBITMQ_PASSWORD=guest
            - RABBITMQ_PORT=5672
            - CELERY_BROKER_URL=pyamqp://guest@rabbitmq//
        ports:
            - 5555:5555
        depends_on:
            - rabbitmq
            - redis